In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import preprocessing
import xgboost as xgb
import random

import sys, gc, warnings, random, datetime

from sklearn import metrics
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error
from tqdm import tqdm
import time
import lightgbm as lgb
import scipy as sc

import math
warnings.filterwarnings('ignore')

import os
print(os.listdir("../input"))

['train_transaction.csv', 'train_identity.csv', 'sample_submission.csv', 'standalone-train-and-test-preprocessing', 'test_identity.csv', 'test_transaction.csv']

In [2]:
train_transaction = pd.read_csv('../input/train_transaction.csv', index_col='TransactionID')
test_transaction = pd.read_csv('../input/test_transaction.csv', index_col='TransactionID')

train_identity = pd.read_csv('../input/train_identity.csv', index_col='TransactionID')
test_identity = pd.read_csv('../input/test_identity.csv', index_col='TransactionID')

sample_submission = pd.read_csv('../input/sample_submission.csv', index_col='TransactionID')

In [3]:
cols = test_transaction.columns
combined_transaction = pd.concat([train_transaction[cols], test_transaction[cols]],axis=0)
combined_transaction.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987000,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987001,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987002,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987003,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987004,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# map
CD_map = combined_transaction['ProductCD'].value_counts().to_dict()   
card4_map = combined_transaction['card4'].value_counts().to_dict()   
card6_map = combined_transaction['card6'].value_counts().to_dict() 
m4_map = combined_transaction['M4'].value_counts().to_dict() 

P_domain_map = combined_transaction['P_emaildomain'].value_counts().to_dict()
for key, value in P_domain_map.items():
    P_domain_map[key] = int(P_domain_map[key] > 2000)

R_domain_map = combined_transaction['R_emaildomain'].value_counts().to_dict()
for key, value in R_domain_map.items():
    R_domain_map[key] = int(R_domain_map[key] > 2000)
    
T_F_map = {'T':1, 'F':0}

def fe(transaction):
    
#     transaction_transformed['day'] = transaction_transformed['TransactionDT'] // 86400

    # create date column
    START_DATE = '2017-12-01'
    startdate = datetime.datetime.strptime(START_DATE, '%Y-%m-%d')
#     transaction['date'] = transaction['TransactionDT'].apply(lambda x: (startdate + datetime.timedelta(seconds = x)))
   
    
    # hour in the day
#     transaction['hour'] = transaction['TransactionDT'] % 86400 // 3600
    
    # transaction amount
    transaction['TransactionAmt'] = transaction['TransactionAmt'].apply(lambda y: y if y <= 10000 else 10000)
    
    # productCD
    # 5 mini-model
    transaction['ProductCD'] = transaction['ProductCD'].map(CD_map)
    
    # card 1-6, card info
    transaction['card4'] = transaction['card4'].map(card4_map)
    transaction['card6'] = transaction['card6'].map(card6_map)
    
    # address, region and county
    
    # dist 1, 2
    transaction['dist1'] = transaction['dist1'].apply(lambda y: y if y <= 3000 else 3000)
    transaction['dist2'] = transaction['dist2'].apply(lambda y: y if y <= 3000 else 3000)
    
    # email domains
    transaction['P_emaildomain'] = transaction['P_emaildomain'].map(P_domain_map)
    transaction['R_emaildomain'] = transaction['R_emaildomain'].map(R_domain_map)
    
    # C1-C14
    transaction['C1'] = transaction['C1'].apply(lambda y: y if y <= 500 else 500)
    transaction['C2'] = transaction['C2'].apply(lambda y: y if y <= 500 else 500)
    transaction['C3'] = transaction['C3'].apply(lambda y: y if y <= 3 else 3)
    transaction['C4'] = transaction['C4'].apply(lambda y: y if y <= 300 else 300)
    transaction['C5'] = transaction['C5'].apply(lambda y: y if y <= 300 else 300)
    transaction['C6'] = transaction['C6'].apply(lambda y: y if y <= 300 else 300)
    transaction['C7'] = transaction['C7'].apply(lambda y: y if y <= 300 else 300)
    transaction['C8'] = transaction['C8'].apply(lambda y: y if y <= 300 else 300)
    transaction['C9'] = transaction['C9'].apply(lambda y: y if y <= 300 else 300)
    transaction['C10'] = transaction['C10'].apply(lambda y: y if y <= 300 else 300)
    transaction['C11'] = transaction['C11'].apply(lambda y: y if y <= 300 else 300)
    transaction['C12'] = transaction['C12'].apply(lambda y: y if y <= 300 else 300)
    transaction['C13'] = transaction['C13'].apply(lambda y: y if y <= 1000 else 1000)
    transaction['C14'] = transaction['C14'].apply(lambda y: y if y <= 300 else 300)
    
    # D1-D15
    transaction['D1'] = transaction['D1'].apply(lambda y: y if y <= 480 else 480)
    transaction['D2'] = transaction['D2'].apply(lambda y: y if y <= 480 else 480)
    transaction['D3'] = transaction['D3'].apply(lambda y: y if y <= 480 else 480)
    transaction['D4'] = transaction['D4'].apply(lambda y: y if y <= 480 else 480)
    transaction['D5'] = transaction['D5'].apply(lambda y: y if y <= 700 else 700)
    transaction['D6'] = transaction['D6'].apply(lambda y: y if y <= 480 else 480)
    transaction['D7'] = transaction['D7'].apply(lambda y: y if y <= 480 else 480)
    transaction['D8'] = transaction['D8'].apply(lambda y: y if y <= 800 else 800)
    transaction['D9'] = transaction['D9'].apply(lambda y: y if y <= 480 else 480)
    transaction['D10'] = transaction['D10'].apply(lambda y: y if y <= 480 else 480)
    transaction['D11'] = transaction['D11'].apply(lambda y: y if y <= 480 else 480)
    transaction['D12'] = transaction['D12'].apply(lambda y: y if y <= 480 else 480)
    transaction['D13'] = transaction['D13'].apply(lambda y: y if y <= 480 else 480)
    transaction['D14'] = transaction['D14'].apply(lambda y: y if y <= 480 else 480)
    transaction['D15'] = transaction['D15'].apply(lambda y: y if y <= 480 else 480)
    
    # M1-M9
    for col in ['M1','M2','M3','M5','M6','M7','M8','M9']:
        transaction[col] = transaction[col].map(T_F_map)
    transaction['M4'] = transaction['M4'].map(m4_map)

    # V1-V340
    transaction['V2'] = transaction['V2'].apply(lambda y: y if y <= 6 else 6)
    transaction['V3'] = transaction['V3'].apply(lambda y: y if y <= 8 else 8)
    transaction['V4'] = transaction['V4'].apply(lambda y: y if y <= 5 else 5)
    transaction['V5'] = transaction['V5'].apply(lambda y: y if y <= 5 else 5)
    transaction['V6'] = transaction['V6'].apply(lambda y: y if y <= 6 else 6)
    transaction['V7'] = transaction['V7'].apply(lambda y: y if y <= 7 else 7)
    transaction['V8'] = transaction['V8'].apply(lambda y: y if y <= 6 else 6)
    transaction['V9'] = transaction['V9'].apply(lambda y: y if y <= 6 else 6)
    transaction['V10'] = transaction['V10'].apply(lambda y: y if y <= 3 else 3)
    transaction['V11'] = transaction['V11'].apply(lambda y: y if y <= 4 else 4)
    transaction['V12'] = transaction['V12'].apply(lambda y: y if y <= 3 else 3)
    transaction['V13'] = transaction['V13'].apply(lambda y: y if y <= 5 else 5)
    transaction['V15'] = transaction['V15'].apply(lambda y: y if y <= 3 else 3)
    transaction['V16'] = transaction['V16'].apply(lambda y: y if y <= 5 else 5)
    transaction['V17'] = transaction['V17'].apply(lambda y: y if y <= 6 else 6)
    transaction['V18'] = transaction['V18'].apply(lambda y: y if y <= 6 else 6)
    transaction['V19'] = transaction['V19'].apply(lambda y: y if y <= 4 else 4)
    transaction['V20'] = transaction['V20'].apply(lambda y: y if y <= 6 else 6)
    transaction['V21'] = transaction['V21'].apply(lambda y: y if y <= 3 else 3)
    transaction['V22'] = transaction['V22'].apply(lambda y: y if y <= 7 else 7)
    transaction['V23'] = transaction['V23'].apply(lambda y: y if y <= 10 else 10)
    transaction['V24'] = transaction['V24'].apply(lambda y: y if y <= 10 else 10)
    transaction['V25'] = transaction['V25'].apply(lambda y: y if y <= 3 else 3)
    transaction['V26'] = transaction['V26'].apply(lambda y: y if y <= 4 else 4)
    transaction['V27'] = transaction['V27'].apply(lambda y: y if y <= 1 else 1)
    transaction['V28'] = transaction['V28'].apply(lambda y: y if y <= 1 else 1)
    transaction['V29'] = transaction['V29'].apply(lambda y: y if y <= 4 else 4)
    transaction['V30'] = transaction['V30'].apply(lambda y: y if y <= 5 else 5)
    transaction['V31'] = transaction['V31'].apply(lambda y: y if y <= 3 else 3)
    transaction['V32'] = transaction['V32'].apply(lambda y: y if y <= 4 else 4)
    transaction['V33'] = transaction['V33'].apply(lambda y: y if y <= 3 else 3)
    transaction['V34'] = transaction['V34'].apply(lambda y: y if y <= 3 else 3)
    transaction['V35'] = transaction['V35'].apply(lambda y: y if y <= 3 else 3)
    transaction['V36'] = transaction['V36'].apply(lambda y: y if y <= 3 else 3)
    transaction['V37'] = transaction['V37'].apply(lambda y: y if y <= 10 else 10)
    transaction['V38'] = transaction['V38'].apply(lambda y: y if y <= 10 else 10)
    transaction['V39'] = transaction['V39'].apply(lambda y: y if y <= 6 else 6)
    transaction['V40'] = transaction['V40'].apply(lambda y: y if y <= 8 else 8)
    transaction['V42'] = transaction['V42'].apply(lambda y: y if y <= 3 else 3)
    transaction['V43'] = transaction['V43'].apply(lambda y: y if y <= 4 else 4)
    transaction['V44'] = transaction['V44'].apply(lambda y: y if y <= 5 else 5)
    transaction['V45'] = transaction['V45'].apply(lambda y: y if y <= 5 else 5)
    transaction['V46'] = transaction['V46'].apply(lambda y: y if y <= 3 else 3)
    transaction['V47'] = transaction['V47'].apply(lambda y: y if y <= 4 else 4)
    transaction['V48'] = transaction['V48'].apply(lambda y: y if y <= 3 else 3)
    transaction['V49'] = transaction['V49'].apply(lambda y: y if y <= 4 else 4)
    transaction['V50'] = transaction['V50'].apply(lambda y: y if y <= 2 else 2)
    transaction['V51'] = transaction['V51'].apply(lambda y: y if y <= 3 else 3)
    transaction['V52'] = transaction['V52'].apply(lambda y: y if y <= 4 else 4)
    transaction['V53'] = transaction['V53'].apply(lambda y: y if y <= 3 else 3)
    transaction['V54'] = transaction['V54'].apply(lambda y: y if y <= 3 else 3)
    transaction['V55'] = transaction['V55'].apply(lambda y: y if y <= 6 else 6)
    transaction['V56'] = transaction['V56'].apply(lambda y: y if y <= 6 else 6)
    transaction['V57'] = transaction['V57'].apply(lambda y: y if y <= 2 else 2)
    transaction['V58'] = transaction['V58'].apply(lambda y: y if y <= 3 else 3)
    transaction['V59'] = transaction['V59'].apply(lambda y: y if y <= 4 else 4)
    transaction['V60'] = transaction['V60'].apply(lambda y: y if y <= 4 else 4)
    transaction['V61'] = transaction['V61'].apply(lambda y: y if y <= 3 else 3)
    transaction['V62'] = transaction['V62'].apply(lambda y: y if y <= 4 else 4)
    transaction['V63'] = transaction['V63'].apply(lambda y: y if y <= 3 else 3)
    transaction['V64'] = transaction['V64'].apply(lambda y: y if y <= 5 else 5)
    transaction['V66'] = transaction['V66'].apply(lambda y: y if y <= 3 else 3)
    transaction['V67'] = transaction['V67'].apply(lambda y: y if y <= 3 else 3)
    transaction['V68'] = transaction['V68'].apply(lambda y: y if y <= 1 else 1)
    transaction['V69'] = transaction['V69'].apply(lambda y: y if y <= 3 else 3)
    transaction['V70'] = transaction['V70'].apply(lambda y: y if y <= 4 else 4)
    transaction['V71'] = transaction['V71'].apply(lambda y: y if y <= 3 else 3)
    transaction['V72'] = transaction['V72'].apply(lambda y: y if y <= 3 else 3)
    transaction['V73'] = transaction['V73'].apply(lambda y: y if y <= 3 else 3)
    transaction['V74'] = transaction['V74'].apply(lambda y: y if y <= 3 else 3)
    transaction['V75'] = transaction['V75'].apply(lambda y: y if y <= 3 else 3)
    transaction['V76'] = transaction['V76'].apply(lambda y: y if y <= 3 else 3)
    transaction['V77'] = transaction['V77'].apply(lambda y: y if y <= 6 else 6)
    transaction['V78'] = transaction['V78'].apply(lambda y: y if y <= 6 else 6)
    transaction['V79'] = transaction['V79'].apply(lambda y: y if y <= 3 else 3)
    transaction['V80'] = transaction['V80'].apply(lambda y: y if y <= 5 else 5)
    transaction['V81'] = transaction['V81'].apply(lambda y: y if y <= 5 else 5)
    transaction['V82'] = transaction['V82'].apply(lambda y: y if y <= 3 else 3)
    transaction['V83'] = transaction['V83'].apply(lambda y: y if y <= 4 else 4)
    transaction['V84'] = transaction['V84'].apply(lambda y: y if y <= 3 else 3)
    transaction['V85'] = transaction['V85'].apply(lambda y: y if y <= 4 else 4)
    transaction['V86'] = transaction['V86'].apply(lambda y: y if y <= 6 else 6)
    transaction['V87'] = transaction['V87'].apply(lambda y: y if y <= 6 else 6)
    transaction['V89'] = transaction['V89'].apply(lambda y: y if y <= 1 else 1)
    transaction['V90'] = transaction['V90'].apply(lambda y: y if y <= 3 else 3)
    transaction['V91'] = transaction['V91'].apply(lambda y: y if y <= 4 else 4)
    transaction['V92'] = transaction['V92'].apply(lambda y: y if y <= 3 else 3)
    transaction['V93'] = transaction['V93'].apply(lambda y: y if y <= 3 else 3)
    transaction['V94'] = transaction['V94'].apply(lambda y: y if y <= 1 else 1)
    transaction['V95'] = transaction['V95'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V96'] = transaction['V96'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V97'] = transaction['V97'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V98'] = transaction['V98'].apply(lambda y: y if y <= 4 else 4)
    transaction['V99'] = transaction['V99'].apply(lambda y: y if y <= 10 else 10)
    transaction['V100'] = transaction['V100'].apply(lambda y: y if y <= 6 else 6)
    transaction['V101'] = transaction['V101'].apply(lambda y: y if y <= 20 else 20) #
    transaction['V102'] = transaction['V102'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V103'] = transaction['V103'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V104'] = transaction['V104'].apply(lambda y: y if y <= 5 else 5)
    transaction['V105'] = transaction['V105'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V106'] = transaction['V106'].apply(lambda y: y if y <= 5 else 5) # 
    transaction['V108'] = transaction['V108'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V109'] = transaction['V109'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V110'] = transaction['V110'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V111'] = transaction['V111'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V112'] = transaction['V112'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V113'] = transaction['V113'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V114'] = transaction['V114'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V115'] = transaction['V115'].apply(lambda y: y if y <= 4 else 4) 
    transaction['V116'] = transaction['V116'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V117'] = transaction['V117'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V118'] = transaction['V118'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V119'] = transaction['V119'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V120'] = transaction['V120'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V121'] = transaction['V121'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V122'] = transaction['V122'].apply(lambda y: y if y <= 2 else 2) #0
    transaction['V123'] = transaction['V123'].apply(lambda y: y if y <= 6 else 6) 
    transaction['V124'] = transaction['V124'].apply(lambda y: y if y <= 6 else 6) 
    transaction['V125'] = transaction['V125'].apply(lambda y: y if y <= 6 else 6) 
    transaction['V126'] = transaction['V126'].apply(lambda y: y if y <= 5000 else 5000) #
    transaction['V127'] = transaction['V127'].apply(lambda y: y if y <= 5000 else 5000) #
    transaction['V128'] = transaction['V128'].apply(lambda y: y if y <= 5000 else 5000) #
    transaction['V129'] = transaction['V129'].apply(lambda y: y if y <= 1000 else 1000) #
    transaction['V130'] = transaction['V130'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V131'] = transaction['V131'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V132'] = transaction['V132'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V133'] = transaction['V133'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V134'] = transaction['V134'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V135'] = transaction['V135'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V136'] = transaction['V136'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V137'] = transaction['V137'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V138'] = transaction['V138'].apply(lambda y: y if y <= 5 else 5)
    transaction['V139'] = transaction['V139'].apply(lambda y: y if y <= 10 else 10)
    transaction['V140'] = transaction['V140'].apply(lambda y: y if y <= 10 else 10)
    transaction['V141'] = transaction['V141'].apply(lambda y: y if y <= 2 else 2)
    transaction['V142'] = transaction['V142'].apply(lambda y: y if y <= 4 else 4)
    transaction['V143'] = transaction['V143'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V144'] = transaction['V144'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V145'] = transaction['V145'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V146'] = transaction['V146'].apply(lambda y: y if y <= 6 else 6)
    transaction['V147'] = transaction['V147'].apply(lambda y: y if y <= 6 else 6)
    transaction['V148'] = transaction['V148'].apply(lambda y: y if y <= 3 else 3)
    transaction['V149'] = transaction['V149'].apply(lambda y: y if y <= 3 else 3)
    transaction['V150'] = transaction['V150'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V151'] = transaction['V151'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V152'] = transaction['V152'].apply(lambda y: y if y <= 8 else 8) #?
    transaction['V153'] = transaction['V153'].apply(lambda y: y if y <= 3 else 3)
    transaction['V154'] = transaction['V154'].apply(lambda y: y if y <= 3 else 3)
    transaction['V155'] = transaction['V155'].apply(lambda y: y if y <= 3 else 3)
    transaction['V156'] = transaction['V156'].apply(lambda y: y if y <= 3 else 3)
    transaction['V157'] = transaction['V157'].apply(lambda y: y if y <= 4 else 4)
    transaction['V158'] = transaction['V158'].apply(lambda y: y if y <= 5 else 5)
    transaction['V159'] = transaction['V159'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V160'] = transaction['V160'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V161'] = transaction['V161'].apply(lambda y: y if y <= 300 else 300)
    transaction['V162'] = transaction['V162'].apply(lambda y: y if y <= 300 else 300)
    transaction['V163'] = transaction['V163'].apply(lambda y: y if y <= 300 else 300)
    transaction['V164'] = transaction['V164'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V165'] = transaction['V165'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V166'] = transaction['V166'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V167'] = transaction['V167'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V168'] = transaction['V168'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V169'] = transaction['V169'].apply(lambda y: y if y <= 10 else 10) 
    transaction['V170'] = transaction['V170'].apply(lambda y: y if y <= 12 else 12) #?
    transaction['V171'] = transaction['V171'].apply(lambda y: y if y <= 12 else 12) #?
    transaction['V172'] = transaction['V172'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V173'] = transaction['V173'].apply(lambda y: y if y <= 2 else 2) 
    transaction['V174'] = transaction['V174'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V175'] = transaction['V175'].apply(lambda y: y if y <= 8 else 8) 
    transaction['V176'] = transaction['V176'].apply(lambda y: y if y <= 12 else 12) #?
    transaction['V177'] = transaction['V177'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V178'] = transaction['V178'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V179'] = transaction['V179'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V180'] = transaction['V180'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V181'] = transaction['V181'].apply(lambda y: y if y <= 5 else 5) #?
    transaction['V182'] = transaction['V182'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V183'] = transaction['V183'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V184'] = transaction['V184'].apply(lambda y: y if y <= 6 else 6)
    transaction['V185'] = transaction['V185'].apply(lambda y: y if y <= 5 else 5) #?
    transaction['V186'] = transaction['V186'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V187'] = transaction['V187'].apply(lambda y: y if y <= 25 else 25) #
    transaction['V188'] = transaction['V188'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V189'] = transaction['V189'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V190'] = transaction['V190'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V191'] = transaction['V191'].apply(lambda y: y if y <= 5 else 5) #?
    transaction['V192'] = transaction['V192'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V193'] = transaction['V193'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V194'] = transaction['V194'].apply(lambda y: y if y <= 3 else 3)
    transaction['V195'] = transaction['V195'].apply(lambda y: y if y <= 3 else 3)
    transaction['V196'] = transaction['V196'].apply(lambda y: y if y <= 5 else 5) #?
    transaction['V197'] = transaction['V197'].apply(lambda y: y if y <= 3 else 3)
    transaction['V198'] = transaction['V198'].apply(lambda y: y if y <= 3 else 3)
    transaction['V199'] = transaction['V199'].apply(lambda y: y if y <= 5 else 5) #?
    transaction['V200'] = transaction['V200'].apply(lambda y: y if y <= 5 else 5)
    transaction['V201'] = transaction['V201'].apply(lambda y: y if y <= 5 else 5)
    transaction['V202'] = transaction['V202'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V203'] = transaction['V203'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V204'] = transaction['V204'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V205'] = transaction['V205'].apply(lambda y: y if y <= 500 else 500)
    transaction['V206'] = transaction['V206'].apply(lambda y: y if y <= 300 else 300)
    transaction['V207'] = transaction['V207'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V208'] = transaction['V208'].apply(lambda y: y if y <= 200 else 200)
    transaction['V209'] = transaction['V209'].apply(lambda y: y if y <= 500 else 500) #
    transaction['V210'] = transaction['V210'].apply(lambda y: y if y <= 500 else 500) #
    transaction['V211'] = transaction['V211'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V212'] = transaction['V212'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V213'] = transaction['V213'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V214'] = transaction['V214'].apply(lambda y: y if y <= 2000 else 2000)
    transaction['V215'] = transaction['V215'].apply(lambda y: y if y <= 2000 else 2000) 
    transaction['V216'] = transaction['V216'].apply(lambda y: y if y <= 2000 else 2000) 
    transaction['V217'] = transaction['V217'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V218'] = transaction['V218'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V219'] = transaction['V219'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V220'] = transaction['V220'].apply(lambda y: y if y <= 10 else 10) 
    transaction['V221'] = transaction['V221'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V222'] = transaction['V222'].apply(lambda y: y if y <= 30 else 30) #
    transaction['V223'] = transaction['V223'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V224'] = transaction['V224'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V225'] = transaction['V225'].apply(lambda y: y if y <= 5 else 5) #
    transaction['V226'] = transaction['V226'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V227'] = transaction['V227'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V228'] = transaction['V228'].apply(lambda y: y if y <= 10 else 10)
    transaction['V229'] = transaction['V229'].apply(lambda y: y if y <= 25 else 25) #
    transaction['V230'] = transaction['V230'].apply(lambda y: y if y <= 10 else 10) #
    transaction['V231'] = transaction['V231'].apply(lambda y: y if y <= 15 else 15) #
    transaction['V232'] = transaction['V232'].apply(lambda y: y if y <= 15 else 15) #
    transaction['V233'] = transaction['V233'].apply(lambda y: y if y <= 15 else 15) #
    transaction['V234'] = transaction['V234'].apply(lambda y: y if y <= 15 else 15) #
    transaction['V235'] = transaction['V235'].apply(lambda y: y if y <= 5 else 5)
    transaction['V236'] = transaction['V236'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V237'] = transaction['V237'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V238'] = transaction['V238'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V239'] = transaction['V239'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V240'] = transaction['V240'].apply(lambda y: y if y <= 2 else 2) 
    transaction['V240'] = transaction['V240'].apply(lambda y: y if y >= 1 else 1) 
    transaction['V241'] = transaction['V241'].apply(lambda y: y if y <= 2 else 2) 
    transaction['V241'] = transaction['V241'].apply(lambda y: y if y >= 1 else 1) 
    transaction['V242'] = transaction['V242'].apply(lambda y: y if y <= 6 else 6)
    transaction['V243'] = transaction['V243'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V244'] = transaction['V244'].apply(lambda y: y if y <= 6 else 6)
    transaction['V245'] = transaction['V245'].apply(lambda y: y if y <= 6 else 6)
    transaction['V246'] = transaction['V246'].apply(lambda y: y if y <= 6 else 6)
    transaction['V247'] = transaction['V247'].apply(lambda y: y if y <= 3 else 3)
    transaction['V248'] = transaction['V248'].apply(lambda y: y if y <= 5 else 5) #
    transaction['V249'] = transaction['V249'].apply(lambda y: y if y <= 4 else 4)
    transaction['V250'] = transaction['V250'].apply(lambda y: y if y <= 3 else 3)
    transaction['V251'] = transaction['V251'].apply(lambda y: y if y <= 3 else 3)
    transaction['V252'] = transaction['V252'].apply(lambda y: y if y <= 5 else 5)
    transaction['V253'] = transaction['V253'].apply(lambda y: y if y <= 6 else 6) # 
    transaction['V254'] = transaction['V254'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V255'] = transaction['V255'].apply(lambda y: y if y <= 5 else 5) #
    transaction['V256'] = transaction['V256'].apply(lambda y: y if y <= 5 else 5) #
    transaction['V257'] = transaction['V257'].apply(lambda y: y if y <= 10 else 10)
    transaction['V258'] = transaction['V258'].apply(lambda y: y if y <= 10 else 10)
    transaction['V259'] = transaction['V259'].apply(lambda y: y if y <= 10 else 10)
    transaction['V260'] = transaction['V260'].apply(lambda y: y if y <= 4 else 4)
    transaction['V261'] = transaction['V261'].apply(lambda y: y if y <= 6 else 6)
    transaction['V262'] = transaction['V262'].apply(lambda y: y if y <= 6 else 6)
    transaction['V263'] = transaction['V263'].apply(lambda y: y if y <= 2000 else 2000)
    transaction['V264'] = transaction['V264'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V265'] = transaction['V265'].apply(lambda y: y if y <= 2000 else 2000) #
    transaction['V266'] = transaction['V266'].apply(lambda y: y if y <= 200 else 200)
    transaction['V267'] = transaction['V267'].apply(lambda y: y if y <= 200 else 200) #
    transaction['V268'] = transaction['V268'].apply(lambda y: y if y <= 200 else 200) #
    transaction['V269'] = transaction['V269'].apply(lambda y: y if y <= 200 else 200) 
    transaction['V270'] = transaction['V270'].apply(lambda y: y if y <= 200 else 200) 
    transaction['V271'] = transaction['V271'].apply(lambda y: y if y <= 200 else 200) #
    transaction['V272'] = transaction['V272'].apply(lambda y: y if y <= 200 else 200) 
    transaction['V273'] = transaction['V273'].apply(lambda y: y if y <= 400 else 400) #
    # ---
    transaction['V274'] = transaction['V274'].apply(lambda y: y if y <= 400 else 400) #
    transaction['V275'] = transaction['V275'].apply(lambda y: y if y <= 400 else 400) #
    transaction['V276'] = transaction['V276'].apply(lambda y: y if y <= 400 else 400) #
    transaction['V277'] = transaction['V277'].apply(lambda y: y if y <= 400 else 400) #
    transaction['V278'] = transaction['V278'].apply(lambda y: y if y <= 400 else 400) #
    transaction['V279'] = transaction['V279'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V280'] = transaction['V274'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V281'] = transaction['V281'].apply(lambda y: y if y <= 6 else 6) #
    transaction['V282'] = transaction['V282'].apply(lambda y: y if y <= 7 else 7) 
    transaction['V283'] = transaction['V283'].apply(lambda y: y if y <= 15 else 15) #
    transaction['V284'] = transaction['V284'].apply(lambda y: y if y <= 4 else 4) 
    transaction['V285'] = transaction['V285'].apply(lambda y: y if y <= 20 else 20) # 
    transaction['V286'] = transaction['V286'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V287'] = transaction['V287'].apply(lambda y: y if y <= 10 else 10) 
    transaction['V288'] = transaction['V288'].apply(lambda y: y if y <= 3 else 3) 
    transaction['V289'] = transaction['V289'].apply(lambda y: y if y <= 5 else 5) 
    transaction['V290'] = transaction['V290'].apply(lambda y: y if y <= 7 else 7) 
    transaction['V291'] = transaction['V291'].apply(lambda y: y if y <= 100 else 100) #
    transaction['V292'] = transaction['V292'].apply(lambda y: y if y <= 50 else 50) #
    transaction['V293'] = transaction['V293'].apply(lambda y: y if y <= 30 else 30) # 
    transaction['V294'] = transaction['V294'].apply(lambda y: y if y <= 50 else 50) # 
    transaction['V295'] = transaction['V295'].apply(lambda y: y if y <= 50 else 50) # 
    transaction['V296'] = transaction['V296'].apply(lambda y: y if y <= 10 else 10) # 
    transaction['V297'] = transaction['V297'].apply(lambda y: y if y <= 5 else 5) # 
    transaction['V298'] = transaction['V298'].apply(lambda y: y if y <= 10 else 10) # 
    transaction['V299'] = transaction['V299'].apply(lambda y: y if y <= 6 else 6) # 
    transaction['V300'] = transaction['V300'].apply(lambda y: y if y <= 5 else 5) # 
    
    # drop irrelavant features
    transaction = transaction.drop(['TransactionDT'],axis=1)
    
    return transaction

In [8]:
train_transaction_transformed = fe(train_transaction)
test_transaction_transformed = fe(test_transaction)

In [9]:
train = train_transaction.merge(train_identity, how='left', left_index=True, right_index=True)
test = test_transaction.merge(test_identity, how='left', left_index=True, right_index=True)

train_y = train['isFraud'].copy()

# Drop target, fill in NaNs
# train_df = train.drop('isFraud', axis=1)
train_df = train.copy()
test_df = test.copy()
# train_df = train_df.fillna(-999)
# test_df = test_df.fillna(-999)

print(train_df.shape)
print(train_y.shape)
print(test_df.shape)

(590540, 433)
(590540,)
(506691, 432)

In [10]:
del train, test, train_transaction, train_identity, test_transaction, test_identity

In [11]:
########################### Helpers
#################################################################################
## -------------------
## Seeder
# :seed to make all processes deterministic     # type: int
def seed_everything(seed=0):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
## ------------------- 

## -------------------
## Memory Reducer
# :df pandas dataframe to reduce size             # type: pd.DataFrame()
# :verbose                                        # type: bool
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df
## -------------------

In [12]:
########################### Vars
#################################################################################
SEED = 42
seed_everything(SEED)
LOCAL_TEST = False

In [13]:
train_df = reduce_mem_usage(train_df)
test_df  = reduce_mem_usage(test_df)

Mem. usage decreased to 572.76 Mb (70.7% reduction)
Mem. usage decreased to 492.88 Mb (70.6% reduction)

In [14]:
# card4, card6, ProductCD
for col in ['card4', 'card6', 'ProductCD']:
    print('Encoding', col)
    temp_df = pd.concat([train_df[[col]], test_df[[col]]])
    col_encoded = temp_df[col].value_counts().to_dict()   
    train_df[col] = train_df[col].map(col_encoded)
    test_df[col]  = test_df[col].map(col_encoded)
    print(col_encoded)

Encoding card4
{719649.0: 719649, 347386.0: 347386, 16009.0: 16009, 9524.0: 9524}
Encoding card6
{824959.0: 824959, 267648.0: 267648, 30.0: 30, 16.0: 16}
Encoding ProductCD
{800657: 800657, 137785: 137785, 73346: 73346, 62397: 62397, 23046: 23046}

In [15]:
# Converting Strings to ints(or floats if nan in column)

for col in ['M1','M2','M3','M5','M6','M7','M8','M9']:
    train_df[col] = train_df[col].map({'T':1, 'F':0})
    test_df[col]  = test_df[col].map({'T':1, 'F':0})

for col in ['M4']:
    print('Encoding', col)
    temp_df = pd.concat([train_df[[col]], test_df[[col]]])
    col_encoded = temp_df[col].value_counts().to_dict()   
    train_df[col] = train_df[col].map(col_encoded)
    test_df[col]  = test_df[col].map(col_encoded)
    print(col_encoded)

Encoding M4
{357789.0: 357789, 122947.0: 122947, 97306.0: 97306}

In [16]:
# Identity columns
map_list = {
    'match_status:2':2,
    'match_status:1':1,
    'match_status:0':0,
    'match_status:-1':-1
}

def minify_identity_df(df):

    df['id_12'] = df['id_12'].map({'Found':1, 'NotFound':0})
    df['id_15'] = df['id_15'].map({'New':2, 'Found':1, 'Unknown':0})
    df['id_16'] = df['id_16'].map({'Found':1, 'NotFound':0})

    df['id_23'] = df['id_23'].map({'IP_PROXY:TRANSPARENT':3, 'IP_PROXY:ANONYMOUS':2, 'IP_PROXY:HIDDEN':1})

    df['id_27'] = df['id_27'].map({'Found':1, 'NotFound':0})
    df['id_28'] = df['id_28'].map({'New':2, 'Found':1})

    df['id_29'] = df['id_29'].map({'Found':1, 'NotFound':0})

    df['id_35'] = df['id_35'].map({'T':1, 'F':0})
    df['id_36'] = df['id_36'].map({'T':1, 'F':0})
    df['id_37'] = df['id_37'].map({'T':1, 'F':0})
    df['id_38'] = df['id_38'].map({'T':1, 'F':0})
    
    df['id_34'] = df['id_34'].map(map_list)
    
#     df['id_34'] = df['id_34'].fillna(':0')
#     df['id_34'] = df['id_34'].apply(lambda x: x.split(':')[1]).astype(np.int8)
#     df['id_34'] = np.where(df['id_34']==0, np.nan, df['id_34'])
    
    df['id_33'] = df['id_33'].fillna('0x0')
    df['id_33_0'] = df['id_33'].apply(lambda x: x.split('x')[0]).astype(int)
    df['id_33_1'] = df['id_33'].apply(lambda x: x.split('x')[1]).astype(int)
    df['id_33'] = np.where(df['id_33']=='0x0', np.nan, df['id_33'])
    df['id_33_area'] = df['id_33_0'] * df['id_33_1']
    
    df['DeviceType'].map({'desktop':1, 'mobile':0})
    return df

train_df = minify_identity_df(train_df)
test_df = minify_identity_df(test_df)

In [17]:
for col in ['id_33']:
    train_df[col] = train_df[col].fillna('unseen_before_label')
    test_df[col]  = test_df[col].fillna('unseen_before_label')
    
    le = preprocessing.LabelEncoder()
    le.fit(list(train_df[col])+list(test_df[col]))
    train_df[col] = le.transform(train_df[col])
    test_df[col]  = le.transform(test_df[col])

In [18]:
train_df = reduce_mem_usage(train_df)
test_df  = reduce_mem_usage(test_df)

Mem. usage decreased to 560.37 Mb (10.0% reduction)
Mem. usage decreased to 482.25 Mb (9.9% reduction)

In [19]:
print(train_df.shape)
print(test_df.shape)

(590540, 436)
(506691, 435)

In [20]:
valid_card = train_df['card1'].value_counts()
valid_card = valid_card[valid_card>10]
valid_card = list(valid_card.index)

In [21]:
train_df['card1'] = np.where(train_df['card1'].isin(valid_card), train_df['card1'], np.nan)
test_df['card1']  = np.where(test_df['card1'].isin(valid_card), test_df['card1'], np.nan)

In [22]:
#---

In [23]:
LOCAL_TEST = False
TARGET = 'isFraud'

In [24]:
########################### Freq encoding
i_cols = ['card1','card2','card3','card5',
          'C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12','C13','C14',
          'D1','D2','D3','D4','D5','D6','D7','D8','D9',
          'addr1','addr2',
          'dist1','dist2',
          'P_emaildomain', 'R_emaildomain'
         ]

for col in i_cols:
    temp_df = pd.concat([train_df[[col]], test_df[[col]]])
    fq_encode = temp_df[col].value_counts().to_dict()   
    train_df[col+'_fq_enc'] = train_df[col].map(fq_encode)
    test_df[col+'_fq_enc']  = test_df[col].map(fq_encode)

In [25]:
########################### ProductCD and M4 Target mean
for col in ['ProductCD','M4']:
    temp_dict = train_df.groupby([col])[TARGET].agg(['mean']).reset_index().rename(
                                                        columns={'mean': col+'_target_mean'})
    temp_dict.index = temp_dict[col].values
    temp_dict = temp_dict[col+'_target_mean'].to_dict()

    train_df[col+'_target_mean'] = train_df[col].map(temp_dict)
    test_df[col+'_target_mean']  = test_df[col].map(temp_dict)

In [26]:
train_df = train_df.fillna(-999)
test_df = test_df.fillna(-999)

In [27]:
########################### Encode Str columns
for col in list(train_df):
    if train_df[col].dtype=='O':
        print(col)
        train_df[col] = train_df[col].fillna('unseen_before_label')
        test_df[col]  = test_df[col].fillna('unseen_before_label')
        
        train_df[col] = train_df[col].astype(str)
        test_df[col] = test_df[col].astype(str)
        
        le = LabelEncoder()
        le.fit(list(train_df[col])+list(test_df[col]))
        train_df[col] = le.transform(train_df[col])
        test_df[col]  = le.transform(test_df[col])
        
        train_df[col] = train_df[col].astype('category')
        test_df[col] = test_df[col].astype('category')

id_30
id_31
DeviceType
DeviceInfo

In [28]:
########################### Model Features 
## We can use set().difference() but order matters
rm_cols = [
    'TransactionID','TransactionDT',TARGET,
]
features_columns = list(train_df)
for col in rm_cols:
    if col in features_columns:
        features_columns.remove(col)

In [29]:
train_df = train_df.drop(['isFraud'],axis=1)

In [30]:
print(train_df.shape)
print(test_df.shape)

(590540, 470)
(506691, 470)

In [31]:
selected_cols = []
for col in train_df.columns:
    if(abs(sc.stats.pearsonr(train_df[col],train_y)[0]) > 0.01):
        selected_cols.append(col)

In [32]:
print(np.array(selected_cols).shape) #147

(413,)

In [33]:
train_df.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,D8_fq_enc,D9_fq_enc,addr1_fq_enc,addr2_fq_enc,dist1_fq_enc,dist2_fq_enc,P_emaildomain_fq_enc,R_emaildomain_fq_enc,ProductCD_target_mean,M4_target_mean
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987000,86400,68.5,800657,13926.0,-999.0,150.0,9524.0,142.0,267648.0,315.0,...,953930,947967,43035.0,956415.0,4707,1023469,-999.0,-999.0,0.020399,0.113739
2987001,86401,29.0,800657,2755.0,404.0,150.0,347386.0,102.0,267648.0,325.0,...,953930,947967,76902.0,956415.0,643996,1023469,911693.0,-999.0,0.020399,0.036649
2987002,86469,59.0,800657,4663.0,490.0,150.0,719649.0,166.0,824959.0,330.0,...,953930,947967,48387.0,956415.0,38,1023469,911693.0,-999.0,0.020399,0.036649
2987003,86499,50.0,800657,18132.0,567.0,150.0,347386.0,117.0,824959.0,476.0,...,953930,947967,17455.0,956415.0,643996,1023469,911693.0,-999.0,0.020399,0.036649
2987004,86506,50.0,62397,4497.0,514.0,150.0,347386.0,102.0,267648.0,420.0,...,953930,947967,7107.0,956415.0,643996,1023469,911693.0,-999.0,0.047662,-999.000000

In [34]:
train_df = train_df[selected_cols]
test_df = test_df[selected_cols]

In [36]:
train_df = train_df.drop(['TransactionDT'],axis=1)
test_df = test_df.drop(['TransactionDT'],axis=1)

In [37]:
print(train_df.shape)
print(test_df.shape)

(590540, 412)
(506691, 412)

In [38]:
n_fold = 5
folds = KFold(n_splits=n_fold, shuffle=False, random_state=42)

In [39]:
lgb_params = {
                    'objective':'binary',
                    'boosting_type':'gbdt',
                    'metric':'auc',
                    'n_jobs':-1,
                    'learning_rate':0.01,
                    'num_leaves': 2**8,
                    'max_depth':16,
                    'tree_learner':'serial',
                    'colsample_bytree': 0.7,
                    'subsample_freq':1,
                    'subsample':1,
                    'n_estimators':2000,
                    'max_bin':255,
                    'verbose':-1,
                    'seed': 42,
                    'early_stopping_rounds':100, 
                }

In [40]:
oof = np.zeros(len(train_df))
prediction = np.zeros(len(test_df))
scores = []
feature_importance = pd.DataFrame()
for fold_n, (train_index, valid_index) in enumerate(folds.split(train_df)):
    print('Fold', fold_n, 'started at', time.ctime())

    X_train, X_valid = train_df.iloc[train_index], train_df.iloc[valid_index]
    y_train, y_valid = train_y.iloc[train_index], train_y.iloc[valid_index]

    model = lgb.LGBMRegressor(**lgb_params)
    model.fit(train_df, train_y, 
            eval_set=[(X_train, y_train), (X_valid, y_valid)], eval_metric='mae',
            verbose=1000, early_stopping_rounds=200)

    y_pred_valid = model.predict(X_valid)
    y_pred = model.predict(test_df, num_iteration=model.best_iteration_)

    oof[valid_index] = y_pred_valid.reshape(-1,)
    scores.append(mean_absolute_error(y_valid, y_pred_valid))

    prediction += y_pred 

    fold_importance = pd.DataFrame()
    fold_importance["feature"] = train_df.columns
    fold_importance["importance"] = model.feature_importances_
    fold_importance["fold"] = fold_n + 1
    feature_importance = pd.concat([feature_importance, fold_importance], axis=0)

prediction /= n_fold
print(' CV mean score: {0:.4f}, std: {1:.4f}.'.format(np.mean(scores), np.std(scores)))
print('----------------------------------------')
feature_importance["importance"] /= n_fold

Fold 0 started at Tue Sep  3 16:18:00 2019
Training until validation scores don't improve for 100 rounds.
[1000]	valid_0's auc: 0.988866	valid_0's l1: 0.0236645	valid_1's auc: 0.989319	valid_1's l1: 0.0194817
[2000]	valid_0's auc: 0.995891	valid_0's l1: 0.0164056	valid_1's auc: 0.99736	valid_1's l1: 0.0131562
Did not meet early stopping. Best iteration is:
[2000]	valid_0's auc: 0.995891	valid_0's l1: 0.0164056	valid_1's auc: 0.99736	valid_1's l1: 0.0131562
Fold 1 started at Tue Sep  3 16:25:31 2019
Training until validation scores don't improve for 100 rounds.
[1000]	valid_0's auc: 0.988788	valid_0's l1: 0.022334	valid_1's auc: 0.989631	valid_1's l1: 0.0248033
[2000]	valid_0's auc: 0.995991	valid_0's l1: 0.015361	valid_1's auc: 0.996642	valid_1's l1: 0.0173345
Did not meet early stopping. Best iteration is:
[2000]	valid_0's auc: 0.995991	valid_0's l1: 0.015361	valid_1's auc: 0.996642	valid_1's l1: 0.0173345
Fold 2 started at Tue Sep  3 16:32:46 2019
Training until validation scores don't improve for 100 rounds.
[1000]	valid_0's auc: 0.989311	valid_0's l1: 0.0226151	valid_1's auc: 0.987726	valid_1's l1: 0.0236792
[2000]	valid_0's auc: 0.996287	valid_0's l1: 0.015545	valid_1's auc: 0.995549	valid_1's l1: 0.0165987
Did not meet early stopping. Best iteration is:
[2000]	valid_0's auc: 0.996287	valid_0's l1: 0.015545	valid_1's auc: 0.995549	valid_1's l1: 0.0165987
Fold 3 started at Tue Sep  3 16:40:17 2019
Training until validation scores don't improve for 100 rounds.
[1000]	valid_0's auc: 0.989	valid_0's l1: 0.0225575	valid_1's auc: 0.988911	valid_1's l1: 0.0239095
[2000]	valid_0's auc: 0.996296	valid_0's l1: 0.0155556	valid_1's auc: 0.995563	valid_1's l1: 0.0165563
Did not meet early stopping. Best iteration is:
[2000]	valid_0's auc: 0.996296	valid_0's l1: 0.0155556	valid_1's auc: 0.995563	valid_1's l1: 0.0165563
Fold 4 started at Tue Sep  3 16:47:56 2019
Training until validation scores don't improve for 100 rounds.
[1000]	valid_0's auc: 0.988944	valid_0's l1: 0.0229685	valid_1's auc: 0.989145	valid_1's l1: 0.0222657
[2000]	valid_0's auc: 0.996229	valid_0's l1: 0.0159114	valid_1's auc: 0.995773	valid_1's l1: 0.0151329
Did not meet early stopping. Best iteration is:
[2000]	valid_0's auc: 0.996229	valid_0's l1: 0.0159114	valid_1's auc: 0.995773	valid_1's l1: 0.0151329
 CV mean score: 0.0158, std: 0.0015.
----------------------------------------

In [41]:
sub = pd.read_csv('../input/sample_submission.csv')
sub['isFraud']=prediction
sub.head()
sub.to_csv('../submissions/submission_9_3.csv', index=False)